/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "trf_msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(trf_msg_Transport, trf_msg_Transport, AUTO)


PB_BIND(trf_msg_Display, trf_msg_Display, AUTO)


PB_BIND(trf_msg_DisplayReq, trf_msg_DisplayReq, AUTO)


PB_BIND(trf_msg_ClientHello, trf_msg_ClientHello, AUTO)


PB_BIND(trf_msg_ServerHello, trf_msg_ServerHello, AUTO)


PB_BIND(trf_msg_ClientCap, trf_msg_ClientCap, AUTO)


PB_BIND(trf_msg_ServerCap, trf_msg_ServerCap, AUTO)


PB_BIND(trf_msg_ClientReq, trf_msg_ClientReq, AUTO)


PB_BIND(trf_msg_ServerAckReq, trf_msg_ServerAckReq, AUTO)


PB_BIND(trf_msg_ClientFrameReq, trf_msg_ClientFrameReq, AUTO)


PB_BIND(trf_msg_ServerAckFrameReq, trf_msg_ServerAckFrameReq, AUTO)


PB_BIND(trf_msg_ClientDisconnect, trf_msg_ClientDisconnect, AUTO)


PB_BIND(trf_msg_MessageWrapper, trf_msg_MessageWrapper, AUTO)



