/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: trf_msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "trf_msg.pb-c.h"
void   trf_msg__apiversion__init
                     (TrfMsg__APIVersion         *message)
{
  static const TrfMsg__APIVersion init_value = TRF_MSG__APIVERSION__INIT;
  *message = init_value;
}
size_t trf_msg__apiversion__get_packed_size
                     (const TrfMsg__APIVersion *message)
{
  assert(message->base.descriptor == &trf_msg__apiversion__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__apiversion__pack
                     (const TrfMsg__APIVersion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__apiversion__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__apiversion__pack_to_buffer
                     (const TrfMsg__APIVersion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__apiversion__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__APIVersion *
       trf_msg__apiversion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__APIVersion *)
     protobuf_c_message_unpack (&trf_msg__apiversion__descriptor,
                                allocator, len, data);
}
void   trf_msg__apiversion__free_unpacked
                     (TrfMsg__APIVersion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__apiversion__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__addr_cand__init
                     (TrfMsg__AddrCand         *message)
{
  static const TrfMsg__AddrCand init_value = TRF_MSG__ADDR_CAND__INIT;
  *message = init_value;
}
size_t trf_msg__addr_cand__get_packed_size
                     (const TrfMsg__AddrCand *message)
{
  assert(message->base.descriptor == &trf_msg__addr_cand__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__addr_cand__pack
                     (const TrfMsg__AddrCand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__addr_cand__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__addr_cand__pack_to_buffer
                     (const TrfMsg__AddrCand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__addr_cand__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__AddrCand *
       trf_msg__addr_cand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__AddrCand *)
     protobuf_c_message_unpack (&trf_msg__addr_cand__descriptor,
                                allocator, len, data);
}
void   trf_msg__addr_cand__free_unpacked
                     (TrfMsg__AddrCand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__addr_cand__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__transport__init
                     (TrfMsg__Transport         *message)
{
  static const TrfMsg__Transport init_value = TRF_MSG__TRANSPORT__INIT;
  *message = init_value;
}
size_t trf_msg__transport__get_packed_size
                     (const TrfMsg__Transport *message)
{
  assert(message->base.descriptor == &trf_msg__transport__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__transport__pack
                     (const TrfMsg__Transport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__transport__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__transport__pack_to_buffer
                     (const TrfMsg__Transport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__transport__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__Transport *
       trf_msg__transport__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__Transport *)
     protobuf_c_message_unpack (&trf_msg__transport__descriptor,
                                allocator, len, data);
}
void   trf_msg__transport__free_unpacked
                     (TrfMsg__Transport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__transport__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__display__init
                     (TrfMsg__Display         *message)
{
  static const TrfMsg__Display init_value = TRF_MSG__DISPLAY__INIT;
  *message = init_value;
}
size_t trf_msg__display__get_packed_size
                     (const TrfMsg__Display *message)
{
  assert(message->base.descriptor == &trf_msg__display__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__display__pack
                     (const TrfMsg__Display *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__display__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__display__pack_to_buffer
                     (const TrfMsg__Display *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__display__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__Display *
       trf_msg__display__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__Display *)
     protobuf_c_message_unpack (&trf_msg__display__descriptor,
                                allocator, len, data);
}
void   trf_msg__display__free_unpacked
                     (TrfMsg__Display *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__display__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__display_req__init
                     (TrfMsg__DisplayReq         *message)
{
  static const TrfMsg__DisplayReq init_value = TRF_MSG__DISPLAY_REQ__INIT;
  *message = init_value;
}
size_t trf_msg__display_req__get_packed_size
                     (const TrfMsg__DisplayReq *message)
{
  assert(message->base.descriptor == &trf_msg__display_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__display_req__pack
                     (const TrfMsg__DisplayReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__display_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__display_req__pack_to_buffer
                     (const TrfMsg__DisplayReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__display_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__DisplayReq *
       trf_msg__display_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__DisplayReq *)
     protobuf_c_message_unpack (&trf_msg__display_req__descriptor,
                                allocator, len, data);
}
void   trf_msg__display_req__free_unpacked
                     (TrfMsg__DisplayReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__display_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__client_hello__init
                     (TrfMsg__ClientHello         *message)
{
  static const TrfMsg__ClientHello init_value = TRF_MSG__CLIENT_HELLO__INIT;
  *message = init_value;
}
size_t trf_msg__client_hello__get_packed_size
                     (const TrfMsg__ClientHello *message)
{
  assert(message->base.descriptor == &trf_msg__client_hello__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__client_hello__pack
                     (const TrfMsg__ClientHello *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__client_hello__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__client_hello__pack_to_buffer
                     (const TrfMsg__ClientHello *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__client_hello__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ClientHello *
       trf_msg__client_hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ClientHello *)
     protobuf_c_message_unpack (&trf_msg__client_hello__descriptor,
                                allocator, len, data);
}
void   trf_msg__client_hello__free_unpacked
                     (TrfMsg__ClientHello *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__client_hello__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__server_hello__init
                     (TrfMsg__ServerHello         *message)
{
  static const TrfMsg__ServerHello init_value = TRF_MSG__SERVER_HELLO__INIT;
  *message = init_value;
}
size_t trf_msg__server_hello__get_packed_size
                     (const TrfMsg__ServerHello *message)
{
  assert(message->base.descriptor == &trf_msg__server_hello__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__server_hello__pack
                     (const TrfMsg__ServerHello *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__server_hello__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__server_hello__pack_to_buffer
                     (const TrfMsg__ServerHello *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__server_hello__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ServerHello *
       trf_msg__server_hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ServerHello *)
     protobuf_c_message_unpack (&trf_msg__server_hello__descriptor,
                                allocator, len, data);
}
void   trf_msg__server_hello__free_unpacked
                     (TrfMsg__ServerHello *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__server_hello__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__server_reject__init
                     (TrfMsg__ServerReject         *message)
{
  static const TrfMsg__ServerReject init_value = TRF_MSG__SERVER_REJECT__INIT;
  *message = init_value;
}
size_t trf_msg__server_reject__get_packed_size
                     (const TrfMsg__ServerReject *message)
{
  assert(message->base.descriptor == &trf_msg__server_reject__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__server_reject__pack
                     (const TrfMsg__ServerReject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__server_reject__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__server_reject__pack_to_buffer
                     (const TrfMsg__ServerReject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__server_reject__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ServerReject *
       trf_msg__server_reject__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ServerReject *)
     protobuf_c_message_unpack (&trf_msg__server_reject__descriptor,
                                allocator, len, data);
}
void   trf_msg__server_reject__free_unpacked
                     (TrfMsg__ServerReject *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__server_reject__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__addr_pf__init
                     (TrfMsg__AddrPF         *message)
{
  static const TrfMsg__AddrPF init_value = TRF_MSG__ADDR_PF__INIT;
  *message = init_value;
}
size_t trf_msg__addr_pf__get_packed_size
                     (const TrfMsg__AddrPF *message)
{
  assert(message->base.descriptor == &trf_msg__addr_pf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__addr_pf__pack
                     (const TrfMsg__AddrPF *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__addr_pf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__addr_pf__pack_to_buffer
                     (const TrfMsg__AddrPF *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__addr_pf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__AddrPF *
       trf_msg__addr_pf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__AddrPF *)
     protobuf_c_message_unpack (&trf_msg__addr_pf__descriptor,
                                allocator, len, data);
}
void   trf_msg__addr_pf__free_unpacked
                     (TrfMsg__AddrPF *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__addr_pf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__client_cap__init
                     (TrfMsg__ClientCap         *message)
{
  static const TrfMsg__ClientCap init_value = TRF_MSG__CLIENT_CAP__INIT;
  *message = init_value;
}
size_t trf_msg__client_cap__get_packed_size
                     (const TrfMsg__ClientCap *message)
{
  assert(message->base.descriptor == &trf_msg__client_cap__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__client_cap__pack
                     (const TrfMsg__ClientCap *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__client_cap__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__client_cap__pack_to_buffer
                     (const TrfMsg__ClientCap *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__client_cap__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ClientCap *
       trf_msg__client_cap__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ClientCap *)
     protobuf_c_message_unpack (&trf_msg__client_cap__descriptor,
                                allocator, len, data);
}
void   trf_msg__client_cap__free_unpacked
                     (TrfMsg__ClientCap *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__client_cap__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__server_cap__init
                     (TrfMsg__ServerCap         *message)
{
  static const TrfMsg__ServerCap init_value = TRF_MSG__SERVER_CAP__INIT;
  *message = init_value;
}
size_t trf_msg__server_cap__get_packed_size
                     (const TrfMsg__ServerCap *message)
{
  assert(message->base.descriptor == &trf_msg__server_cap__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__server_cap__pack
                     (const TrfMsg__ServerCap *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__server_cap__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__server_cap__pack_to_buffer
                     (const TrfMsg__ServerCap *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__server_cap__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ServerCap *
       trf_msg__server_cap__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ServerCap *)
     protobuf_c_message_unpack (&trf_msg__server_cap__descriptor,
                                allocator, len, data);
}
void   trf_msg__server_cap__free_unpacked
                     (TrfMsg__ServerCap *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__server_cap__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__endpoint__init
                     (TrfMsg__Endpoint         *message)
{
  static const TrfMsg__Endpoint init_value = TRF_MSG__ENDPOINT__INIT;
  *message = init_value;
}
size_t trf_msg__endpoint__get_packed_size
                     (const TrfMsg__Endpoint *message)
{
  assert(message->base.descriptor == &trf_msg__endpoint__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__endpoint__pack
                     (const TrfMsg__Endpoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__endpoint__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__endpoint__pack_to_buffer
                     (const TrfMsg__Endpoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__endpoint__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__Endpoint *
       trf_msg__endpoint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__Endpoint *)
     protobuf_c_message_unpack (&trf_msg__endpoint__descriptor,
                                allocator, len, data);
}
void   trf_msg__endpoint__free_unpacked
                     (TrfMsg__Endpoint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__endpoint__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__client_disp_req__init
                     (TrfMsg__ClientDispReq         *message)
{
  static const TrfMsg__ClientDispReq init_value = TRF_MSG__CLIENT_DISP_REQ__INIT;
  *message = init_value;
}
size_t trf_msg__client_disp_req__get_packed_size
                     (const TrfMsg__ClientDispReq *message)
{
  assert(message->base.descriptor == &trf_msg__client_disp_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__client_disp_req__pack
                     (const TrfMsg__ClientDispReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__client_disp_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__client_disp_req__pack_to_buffer
                     (const TrfMsg__ClientDispReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__client_disp_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ClientDispReq *
       trf_msg__client_disp_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ClientDispReq *)
     protobuf_c_message_unpack (&trf_msg__client_disp_req__descriptor,
                                allocator, len, data);
}
void   trf_msg__client_disp_req__free_unpacked
                     (TrfMsg__ClientDispReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__client_disp_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__server_disp__init
                     (TrfMsg__ServerDisp         *message)
{
  static const TrfMsg__ServerDisp init_value = TRF_MSG__SERVER_DISP__INIT;
  *message = init_value;
}
size_t trf_msg__server_disp__get_packed_size
                     (const TrfMsg__ServerDisp *message)
{
  assert(message->base.descriptor == &trf_msg__server_disp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__server_disp__pack
                     (const TrfMsg__ServerDisp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__server_disp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__server_disp__pack_to_buffer
                     (const TrfMsg__ServerDisp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__server_disp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ServerDisp *
       trf_msg__server_disp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ServerDisp *)
     protobuf_c_message_unpack (&trf_msg__server_disp__descriptor,
                                allocator, len, data);
}
void   trf_msg__server_disp__free_unpacked
                     (TrfMsg__ServerDisp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__server_disp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__client_req__init
                     (TrfMsg__ClientReq         *message)
{
  static const TrfMsg__ClientReq init_value = TRF_MSG__CLIENT_REQ__INIT;
  *message = init_value;
}
size_t trf_msg__client_req__get_packed_size
                     (const TrfMsg__ClientReq *message)
{
  assert(message->base.descriptor == &trf_msg__client_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__client_req__pack
                     (const TrfMsg__ClientReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__client_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__client_req__pack_to_buffer
                     (const TrfMsg__ClientReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__client_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ClientReq *
       trf_msg__client_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ClientReq *)
     protobuf_c_message_unpack (&trf_msg__client_req__descriptor,
                                allocator, len, data);
}
void   trf_msg__client_req__free_unpacked
                     (TrfMsg__ClientReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__client_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__server_ack_req__init
                     (TrfMsg__ServerAckReq         *message)
{
  static const TrfMsg__ServerAckReq init_value = TRF_MSG__SERVER_ACK_REQ__INIT;
  *message = init_value;
}
size_t trf_msg__server_ack_req__get_packed_size
                     (const TrfMsg__ServerAckReq *message)
{
  assert(message->base.descriptor == &trf_msg__server_ack_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__server_ack_req__pack
                     (const TrfMsg__ServerAckReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__server_ack_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__server_ack_req__pack_to_buffer
                     (const TrfMsg__ServerAckReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__server_ack_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ServerAckReq *
       trf_msg__server_ack_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ServerAckReq *)
     protobuf_c_message_unpack (&trf_msg__server_ack_req__descriptor,
                                allocator, len, data);
}
void   trf_msg__server_ack_req__free_unpacked
                     (TrfMsg__ServerAckReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__server_ack_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__client_freq__init
                     (TrfMsg__ClientFReq         *message)
{
  static const TrfMsg__ClientFReq init_value = TRF_MSG__CLIENT_FREQ__INIT;
  *message = init_value;
}
size_t trf_msg__client_freq__get_packed_size
                     (const TrfMsg__ClientFReq *message)
{
  assert(message->base.descriptor == &trf_msg__client_freq__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__client_freq__pack
                     (const TrfMsg__ClientFReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__client_freq__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__client_freq__pack_to_buffer
                     (const TrfMsg__ClientFReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__client_freq__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ClientFReq *
       trf_msg__client_freq__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ClientFReq *)
     protobuf_c_message_unpack (&trf_msg__client_freq__descriptor,
                                allocator, len, data);
}
void   trf_msg__client_freq__free_unpacked
                     (TrfMsg__ClientFReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__client_freq__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__server_ack_freq__init
                     (TrfMsg__ServerAckFReq         *message)
{
  static const TrfMsg__ServerAckFReq init_value = TRF_MSG__SERVER_ACK_FREQ__INIT;
  *message = init_value;
}
size_t trf_msg__server_ack_freq__get_packed_size
                     (const TrfMsg__ServerAckFReq *message)
{
  assert(message->base.descriptor == &trf_msg__server_ack_freq__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__server_ack_freq__pack
                     (const TrfMsg__ServerAckFReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__server_ack_freq__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__server_ack_freq__pack_to_buffer
                     (const TrfMsg__ServerAckFReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__server_ack_freq__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ServerAckFReq *
       trf_msg__server_ack_freq__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ServerAckFReq *)
     protobuf_c_message_unpack (&trf_msg__server_ack_freq__descriptor,
                                allocator, len, data);
}
void   trf_msg__server_ack_freq__free_unpacked
                     (TrfMsg__ServerAckFReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__server_ack_freq__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__disconnect__init
                     (TrfMsg__Disconnect         *message)
{
  static const TrfMsg__Disconnect init_value = TRF_MSG__DISCONNECT__INIT;
  *message = init_value;
}
size_t trf_msg__disconnect__get_packed_size
                     (const TrfMsg__Disconnect *message)
{
  assert(message->base.descriptor == &trf_msg__disconnect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__disconnect__pack
                     (const TrfMsg__Disconnect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__disconnect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__disconnect__pack_to_buffer
                     (const TrfMsg__Disconnect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__disconnect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__Disconnect *
       trf_msg__disconnect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__Disconnect *)
     protobuf_c_message_unpack (&trf_msg__disconnect__descriptor,
                                allocator, len, data);
}
void   trf_msg__disconnect__free_unpacked
                     (TrfMsg__Disconnect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__disconnect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__channel_open__init
                     (TrfMsg__ChannelOpen         *message)
{
  static const TrfMsg__ChannelOpen init_value = TRF_MSG__CHANNEL_OPEN__INIT;
  *message = init_value;
}
size_t trf_msg__channel_open__get_packed_size
                     (const TrfMsg__ChannelOpen *message)
{
  assert(message->base.descriptor == &trf_msg__channel_open__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__channel_open__pack
                     (const TrfMsg__ChannelOpen *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__channel_open__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__channel_open__pack_to_buffer
                     (const TrfMsg__ChannelOpen *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__channel_open__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__ChannelOpen *
       trf_msg__channel_open__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__ChannelOpen *)
     protobuf_c_message_unpack (&trf_msg__channel_open__descriptor,
                                allocator, len, data);
}
void   trf_msg__channel_open__free_unpacked
                     (TrfMsg__ChannelOpen *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__channel_open__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trf_msg__message_wrapper__init
                     (TrfMsg__MessageWrapper         *message)
{
  static const TrfMsg__MessageWrapper init_value = TRF_MSG__MESSAGE_WRAPPER__INIT;
  *message = init_value;
}
size_t trf_msg__message_wrapper__get_packed_size
                     (const TrfMsg__MessageWrapper *message)
{
  assert(message->base.descriptor == &trf_msg__message_wrapper__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trf_msg__message_wrapper__pack
                     (const TrfMsg__MessageWrapper *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trf_msg__message_wrapper__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trf_msg__message_wrapper__pack_to_buffer
                     (const TrfMsg__MessageWrapper *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trf_msg__message_wrapper__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrfMsg__MessageWrapper *
       trf_msg__message_wrapper__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrfMsg__MessageWrapper *)
     protobuf_c_message_unpack (&trf_msg__message_wrapper__descriptor,
                                allocator, len, data);
}
void   trf_msg__message_wrapper__free_unpacked
                     (TrfMsg__MessageWrapper *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trf_msg__message_wrapper__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor trf_msg__apiversion__field_descriptors[3] =
{
  {
    "api_major",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__APIVersion, api_major),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "api_minor",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__APIVersion, api_minor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "api_patch",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__APIVersion, api_patch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__apiversion__field_indices_by_name[] = {
  0,   /* field[0] = api_major */
  1,   /* field[1] = api_minor */
  2,   /* field[2] = api_patch */
};
static const ProtobufCIntRange trf_msg__apiversion__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor trf_msg__apiversion__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.APIVersion",
  "APIVersion",
  "TrfMsg__APIVersion",
  "trfMsg",
  sizeof(TrfMsg__APIVersion),
  3,
  trf_msg__apiversion__field_descriptors,
  trf_msg__apiversion__field_indices_by_name,
  1,  trf_msg__apiversion__number_ranges,
  (ProtobufCMessageInit) trf_msg__apiversion__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__addr_cand__field_descriptors[4] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__AddrCand, addr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "netmask",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__AddrCand, netmask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__AddrCand, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__AddrCand, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__addr_cand__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  1,   /* field[1] = netmask */
  2,   /* field[2] = port */
  3,   /* field[3] = speed */
};
static const ProtobufCIntRange trf_msg__addr_cand__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor trf_msg__addr_cand__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.AddrCand",
  "AddrCand",
  "TrfMsg__AddrCand",
  "trfMsg",
  sizeof(TrfMsg__AddrCand),
  4,
  trf_msg__addr_cand__field_descriptors,
  trf_msg__addr_cand__field_indices_by_name,
  1,  trf_msg__addr_cand__number_ranges,
  (ProtobufCMessageInit) trf_msg__addr_cand__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__transport__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Transport, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Transport, proto),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Transport, route),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__transport__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = proto */
  2,   /* field[2] = route */
};
static const ProtobufCIntRange trf_msg__transport__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor trf_msg__transport__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.Transport",
  "Transport",
  "TrfMsg__Transport",
  "trfMsg",
  sizeof(TrfMsg__Transport),
  3,
  trf_msg__transport__field_descriptors,
  trf_msg__transport__field_indices_by_name,
  1,  trf_msg__transport__number_ranges,
  (ProtobufCMessageInit) trf_msg__transport__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__display__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Display, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Display, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Display, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Display, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Display, rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tex_fmt",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TrfMsg__Display, n_tex_fmt),
    offsetof(TrfMsg__Display, tex_fmt),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dgid",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Display, dgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x_offset",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Display, x_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y_offset",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Display, y_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__display__field_indices_by_name[] = {
  6,   /* field[6] = dgid */
  3,   /* field[3] = height */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  4,   /* field[4] = rate */
  5,   /* field[5] = tex_fmt */
  2,   /* field[2] = width */
  7,   /* field[7] = x_offset */
  8,   /* field[8] = y_offset */
};
static const ProtobufCIntRange trf_msg__display__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 6 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor trf_msg__display__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.Display",
  "Display",
  "TrfMsg__Display",
  "trfMsg",
  sizeof(TrfMsg__Display),
  9,
  trf_msg__display__field_descriptors,
  trf_msg__display__field_indices_by_name,
  2,  trf_msg__display__number_ranges,
  (ProtobufCMessageInit) trf_msg__display__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__display_req__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__DisplayReq, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__DisplayReq, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__DisplayReq, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tex_fmt",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__DisplayReq, tex_fmt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__display_req__field_indices_by_name[] = {
  2,   /* field[2] = height */
  0,   /* field[0] = id */
  3,   /* field[3] = tex_fmt */
  1,   /* field[1] = width */
};
static const ProtobufCIntRange trf_msg__display_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor trf_msg__display_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.DisplayReq",
  "DisplayReq",
  "TrfMsg__DisplayReq",
  "trfMsg",
  sizeof(TrfMsg__DisplayReq),
  4,
  trf_msg__display_req__field_descriptors,
  trf_msg__display_req__field_indices_by_name,
  1,  trf_msg__display_req__number_ranges,
  (ProtobufCMessageInit) trf_msg__display_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__client_hello__field_descriptors[1] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ClientHello, version),
    &trf_msg__apiversion__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__client_hello__field_indices_by_name[] = {
  0,   /* field[0] = version */
};
static const ProtobufCIntRange trf_msg__client_hello__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__client_hello__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ClientHello",
  "ClientHello",
  "TrfMsg__ClientHello",
  "trfMsg",
  sizeof(TrfMsg__ClientHello),
  1,
  trf_msg__client_hello__field_descriptors,
  trf_msg__client_hello__field_indices_by_name,
  1,  trf_msg__client_hello__number_ranges,
  (ProtobufCMessageInit) trf_msg__client_hello__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__server_hello__field_descriptors[1] =
{
  {
    "new_session_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ServerHello, new_session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__server_hello__field_indices_by_name[] = {
  0,   /* field[0] = new_session_id */
};
static const ProtobufCIntRange trf_msg__server_hello__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__server_hello__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ServerHello",
  "ServerHello",
  "TrfMsg__ServerHello",
  "trfMsg",
  sizeof(TrfMsg__ServerHello),
  1,
  trf_msg__server_hello__field_descriptors,
  trf_msg__server_hello__field_indices_by_name,
  1,  trf_msg__server_hello__number_ranges,
  (ProtobufCMessageInit) trf_msg__server_hello__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__server_reject__field_descriptors[1] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ServerReject, version),
    &trf_msg__apiversion__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__server_reject__field_indices_by_name[] = {
  0,   /* field[0] = version */
};
static const ProtobufCIntRange trf_msg__server_reject__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__server_reject__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ServerReject",
  "ServerReject",
  "TrfMsg__ServerReject",
  "trfMsg",
  sizeof(TrfMsg__ServerReject),
  1,
  trf_msg__server_reject__field_descriptors,
  trf_msg__server_reject__field_indices_by_name,
  1,  trf_msg__server_reject__number_ranges,
  (ProtobufCMessageInit) trf_msg__server_reject__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__addr_pf__field_descriptors[1] =
{
  {
    "addrs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__AddrPF, n_addrs),
    offsetof(TrfMsg__AddrPF, addrs),
    &trf_msg__addr_cand__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__addr_pf__field_indices_by_name[] = {
  0,   /* field[0] = addrs */
};
static const ProtobufCIntRange trf_msg__addr_pf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__addr_pf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.AddrPF",
  "AddrPF",
  "TrfMsg__AddrPF",
  "trfMsg",
  sizeof(TrfMsg__AddrPF),
  1,
  trf_msg__addr_pf__field_descriptors,
  trf_msg__addr_pf__field_indices_by_name,
  1,  trf_msg__addr_pf__number_ranges,
  (ProtobufCMessageInit) trf_msg__addr_pf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__client_cap__field_descriptors[1] =
{
  {
    "transports",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__ClientCap, n_transports),
    offsetof(TrfMsg__ClientCap, transports),
    &trf_msg__transport__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__client_cap__field_indices_by_name[] = {
  0,   /* field[0] = transports */
};
static const ProtobufCIntRange trf_msg__client_cap__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__client_cap__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ClientCap",
  "ClientCap",
  "TrfMsg__ClientCap",
  "trfMsg",
  sizeof(TrfMsg__ClientCap),
  1,
  trf_msg__client_cap__field_descriptors,
  trf_msg__client_cap__field_indices_by_name,
  1,  trf_msg__client_cap__number_ranges,
  (ProtobufCMessageInit) trf_msg__client_cap__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__server_cap__field_descriptors[2] =
{
  {
    "bind_addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ServerCap, bind_addr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transport",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ServerCap, transport),
    &trf_msg__transport__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__server_cap__field_indices_by_name[] = {
  0,   /* field[0] = bind_addr */
  1,   /* field[1] = transport */
};
static const ProtobufCIntRange trf_msg__server_cap__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor trf_msg__server_cap__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ServerCap",
  "ServerCap",
  "TrfMsg__ServerCap",
  "trfMsg",
  sizeof(TrfMsg__ServerCap),
  2,
  trf_msg__server_cap__field_descriptors,
  trf_msg__server_cap__field_indices_by_name,
  1,  trf_msg__server_cap__number_ranges,
  (ProtobufCMessageInit) trf_msg__server_cap__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__endpoint__field_descriptors[1] =
{
  {
    "Transport",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Endpoint, transport),
    &trf_msg__transport__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__endpoint__field_indices_by_name[] = {
  0,   /* field[0] = Transport */
};
static const ProtobufCIntRange trf_msg__endpoint__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__endpoint__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.Endpoint",
  "Endpoint",
  "TrfMsg__Endpoint",
  "trfMsg",
  sizeof(TrfMsg__Endpoint),
  1,
  trf_msg__endpoint__field_descriptors,
  trf_msg__endpoint__field_indices_by_name,
  1,  trf_msg__endpoint__number_ranges,
  (ProtobufCMessageInit) trf_msg__endpoint__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__client_disp_req__field_descriptors[1] =
{
  {
    "info",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ClientDispReq, info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__client_disp_req__field_indices_by_name[] = {
  0,   /* field[0] = info */
};
static const ProtobufCIntRange trf_msg__client_disp_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__client_disp_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ClientDispReq",
  "ClientDispReq",
  "TrfMsg__ClientDispReq",
  "trfMsg",
  sizeof(TrfMsg__ClientDispReq),
  1,
  trf_msg__client_disp_req__field_descriptors,
  trf_msg__client_disp_req__field_indices_by_name,
  1,  trf_msg__client_disp_req__number_ranges,
  (ProtobufCMessageInit) trf_msg__client_disp_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__server_disp__field_descriptors[1] =
{
  {
    "displays",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__ServerDisp, n_displays),
    offsetof(TrfMsg__ServerDisp, displays),
    &trf_msg__display__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__server_disp__field_indices_by_name[] = {
  0,   /* field[0] = displays */
};
static const ProtobufCIntRange trf_msg__server_disp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__server_disp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ServerDisp",
  "ServerDisp",
  "TrfMsg__ServerDisp",
  "trfMsg",
  sizeof(TrfMsg__ServerDisp),
  1,
  trf_msg__server_disp__field_descriptors,
  trf_msg__server_disp__field_indices_by_name,
  1,  trf_msg__server_disp__number_ranges,
  (ProtobufCMessageInit) trf_msg__server_disp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__client_req__field_descriptors[1] =
{
  {
    "display",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__ClientReq, n_display),
    offsetof(TrfMsg__ClientReq, display),
    &trf_msg__display_req__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__client_req__field_indices_by_name[] = {
  0,   /* field[0] = display */
};
static const ProtobufCIntRange trf_msg__client_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__client_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ClientReq",
  "ClientReq",
  "TrfMsg__ClientReq",
  "trfMsg",
  sizeof(TrfMsg__ClientReq),
  1,
  trf_msg__client_req__field_descriptors,
  trf_msg__client_req__field_indices_by_name,
  1,  trf_msg__client_req__number_ranges,
  (ProtobufCMessageInit) trf_msg__client_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__server_ack_req__field_descriptors[1] =
{
  {
    "display_ids",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TrfMsg__ServerAckReq, n_display_ids),
    offsetof(TrfMsg__ServerAckReq, display_ids),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__server_ack_req__field_indices_by_name[] = {
  0,   /* field[0] = display_ids */
};
static const ProtobufCIntRange trf_msg__server_ack_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__server_ack_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ServerAckReq",
  "ServerAckReq",
  "TrfMsg__ServerAckReq",
  "trfMsg",
  sizeof(TrfMsg__ServerAckReq),
  1,
  trf_msg__server_ack_req__field_descriptors,
  trf_msg__server_ack_req__field_indices_by_name,
  1,  trf_msg__server_ack_req__number_ranges,
  (ProtobufCMessageInit) trf_msg__server_ack_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__client_freq__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ClientFReq, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_cntr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ClientFReq, frame_cntr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ClientFReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rkey",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ClientFReq, rkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__client_freq__field_indices_by_name[] = {
  2,   /* field[2] = addr */
  1,   /* field[1] = frame_cntr */
  0,   /* field[0] = id */
  3,   /* field[3] = rkey */
};
static const ProtobufCIntRange trf_msg__client_freq__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor trf_msg__client_freq__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ClientFReq",
  "ClientFReq",
  "TrfMsg__ClientFReq",
  "trfMsg",
  sizeof(TrfMsg__ClientFReq),
  4,
  trf_msg__client_freq__field_descriptors,
  trf_msg__client_freq__field_indices_by_name,
  1,  trf_msg__client_freq__number_ranges,
  (ProtobufCMessageInit) trf_msg__client_freq__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__server_ack_freq__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ServerAckFReq, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_cntr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ServerAckFReq, frame_cntr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__server_ack_freq__field_indices_by_name[] = {
  1,   /* field[1] = frame_cntr */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange trf_msg__server_ack_freq__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor trf_msg__server_ack_freq__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ServerAckFReq",
  "ServerAckFReq",
  "TrfMsg__ServerAckFReq",
  "trfMsg",
  sizeof(TrfMsg__ServerAckFReq),
  2,
  trf_msg__server_ack_freq__field_descriptors,
  trf_msg__server_ack_freq__field_indices_by_name,
  1,  trf_msg__server_ack_freq__number_ranges,
  (ProtobufCMessageInit) trf_msg__server_ack_freq__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__disconnect__field_descriptors[1] =
{
  {
    "info",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__Disconnect, info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__disconnect__field_indices_by_name[] = {
  0,   /* field[0] = info */
};
static const ProtobufCIntRange trf_msg__disconnect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__disconnect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.Disconnect",
  "Disconnect",
  "TrfMsg__Disconnect",
  "trfMsg",
  sizeof(TrfMsg__Disconnect),
  1,
  trf_msg__disconnect__field_descriptors,
  trf_msg__disconnect__field_indices_by_name,
  1,  trf_msg__disconnect__number_ranges,
  (ProtobufCMessageInit) trf_msg__disconnect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__channel_open__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__ChannelOpen, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__channel_open__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange trf_msg__channel_open__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trf_msg__channel_open__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.ChannelOpen",
  "ChannelOpen",
  "TrfMsg__ChannelOpen",
  "trfMsg",
  sizeof(TrfMsg__ChannelOpen),
  1,
  trf_msg__channel_open__field_descriptors,
  trf_msg__channel_open__field_indices_by_name,
  1,  trf_msg__channel_open__number_ranges,
  (ProtobufCMessageInit) trf_msg__channel_open__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trf_msg__message_wrapper__field_descriptors[16] =
{
  {
    "session_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TrfMsg__MessageWrapper, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_hello",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, client_hello),
    &trf_msg__client_hello__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_hello",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, server_hello),
    &trf_msg__server_hello__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_reject",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, server_reject),
    &trf_msg__server_reject__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disconnect",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, disconnect),
    &trf_msg__disconnect__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_cap",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, client_cap),
    &trf_msg__client_cap__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_cap",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, server_cap),
    &trf_msg__server_cap__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endpoint",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, endpoint),
    &trf_msg__endpoint__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_disp_req",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, client_disp_req),
    &trf_msg__client_disp_req__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_disp",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, server_disp),
    &trf_msg__server_disp__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_req",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, client_req),
    &trf_msg__client_req__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_ack",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, server_ack),
    &trf_msg__server_ack_req__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_f_req",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, client_f_req),
    &trf_msg__client_freq__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_ack_f_req",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, server_ack_f_req),
    &trf_msg__server_ack_freq__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr_pf",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, addr_pf),
    &trf_msg__addr_pf__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch_open",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrfMsg__MessageWrapper, wdata_case),
    offsetof(TrfMsg__MessageWrapper, ch_open),
    &trf_msg__channel_open__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trf_msg__message_wrapper__field_indices_by_name[] = {
  14,   /* field[14] = addr_pf */
  15,   /* field[15] = ch_open */
  5,   /* field[5] = client_cap */
  8,   /* field[8] = client_disp_req */
  12,   /* field[12] = client_f_req */
  1,   /* field[1] = client_hello */
  10,   /* field[10] = client_req */
  4,   /* field[4] = disconnect */
  7,   /* field[7] = endpoint */
  11,   /* field[11] = server_ack */
  13,   /* field[13] = server_ack_f_req */
  6,   /* field[6] = server_cap */
  9,   /* field[9] = server_disp */
  2,   /* field[2] = server_hello */
  3,   /* field[3] = server_reject */
  0,   /* field[0] = session_id */
};
static const ProtobufCIntRange trf_msg__message_wrapper__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 4 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor trf_msg__message_wrapper__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trfMsg.MessageWrapper",
  "MessageWrapper",
  "TrfMsg__MessageWrapper",
  "trfMsg",
  sizeof(TrfMsg__MessageWrapper),
  16,
  trf_msg__message_wrapper__field_descriptors,
  trf_msg__message_wrapper__field_indices_by_name,
  2,  trf_msg__message_wrapper__number_ranges,
  (ProtobufCMessageInit) trf_msg__message_wrapper__init,
  NULL,NULL,NULL    /* reserved[123] */
};
